export const alphabet = uri => ({
  name_es: 'ALFABETO DACTILOLÓGICO',
  icon: require('../res/icon/alfabeto-dactilologico.png'),
  videos: [
    {
      name_es: 'ALFABETO DACTILOLÓGICO',
      search_name_es: 'ALFABETO DACTILOLOGICO',
      image: require('../res/image/alfabeto-dactilologico.png'),
      video: `${uri}/alfabeto-dactilologico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Aa',
      search_name_es: 'AA',
      image: require('../res/image/a.png'),
      video: `${uri}/a.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Bb',
      search_name_es: 'BB',
      image: require('../res/image/b.png'),
      video: `${uri}/b.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Cc',
      search_name_es: 'CC',
      image: require('../res/image/c.png'),
      video: `${uri}/c.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHch',
      search_name_es: 'CHCH',
      image: require('../res/image/ch.png'),
      video: `${uri}/ch.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Dd',
      search_name_es: 'DD',
      image: require('../res/image/d.png'),
      video: `${uri}/d.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ee',
      search_name_es: 'EE',
      image: require('../res/image/e.png'),
      video: `${uri}/e.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ff',
      search_name_es: 'FF',
      image: require('../res/image/f.png'),
      video: `${uri}/f.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Gg',
      search_name_es: 'GG',
      image: require('../res/image/g.png'),
      video: `${uri}/g.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Hh',
      search_name_es: 'HH',
      image: require('../res/image/h.png'),
      video: `${uri}/h.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ii',
      search_name_es: 'II',
      image: require('../res/image/i.png'),
      video: `${uri}/i.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Jj',
      search_name_es: 'JJ',
      image: require('../res/image/j.png'),
      video: `${uri}/j.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Kk',
      search_name_es: 'KK',
      image: require('../res/image/k.png'),
      video: `${uri}/k.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ll',
      search_name_es: 'LL',
      image: require('../res/image/l.png'),
      video: `${uri}/l.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLll',
      search_name_es: 'LLLL',
      image: require('../res/image/ll.png'),
      video: `${uri}/ll.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Mm',
      search_name_es: 'MM',
      image: require('../res/image/m.png'),
      video: `${uri}/m.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Nn',
      search_name_es: 'NN',
      image: require('../res/image/n.png'),
      video: `${uri}/n.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ññ',
      search_name_es: 'ÑÑ',
      image: require('../res/image/enie.png'),
      video: `${uri}/enie.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Oo',
      search_name_es: 'OO',
      image: require('../res/image/o.png'),
      video: `${uri}/o.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Pp',
      search_name_es: 'PP',
      image: require('../res/image/p.png'),
      video: `${uri}/p.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Qq',
      search_name_es: 'QQ',
      image: require('../res/image/q.png'),
      video: `${uri}/q.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Rr',
      search_name_es: 'RR',
      image: require('../res/image/r.png'),
      video: `${uri}/r.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ss',
      search_name_es: 'SS',
      image: require('../res/image/s.png'),
      video: `${uri}/s.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Tt',
      search_name_es: 'TT',
      image: require('../res/image/t.png'),
      video: `${uri}/t.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Uu',
      search_name_es: 'UU',
      image: require('../res/image/u.png'),
      video: `${uri}/u.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Vv',
      search_name_es: 'VV',
      image: require('../res/image/v.png'),
      video: `${uri}/v.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Ww',
      search_name_es: 'WW',
      image: require('../res/image/w.png'),
      video: `${uri}/w.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Xx',
      search_name_es: 'XX',
      image: require('../res/image/x.png'),
      video: `${uri}/x.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Yy',
      search_name_es: 'YY',
      image: require('../res/image/y.png'),
      video: `${uri}/y.mp4`,
      downloaded: false,
    },
    {
      name_es: 'Zz',
      search_name_es: 'ZZ',
      image: require('../res/image/z.png'),
      video: `${uri}/z.mp4`,
      downloaded: false,
    },
  ],
});
