export const animals = uri => ({
  name_es: 'ANIMALES',
  icon: require('../res/icon/los-animales.png'),
  videos: [
    {
      name_es: 'ANIMALES',
      search_name_es: 'ANIMALES',
      image: require('../res/image/animales.png'),
      video: `${uri}/animales.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARAÑA',
      search_name_es: 'ARAÑA',
      image: require('../res/image/arana.png'),
      video: `${uri}/arana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BURRO',
      search_name_es: 'BURRO',
      image: require('../res/image/burro.png'),
      video: `${uri}/burro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CABALLO',
      search_name_es: 'CABALLO',
      image: require('../res/image/caballo.png'),
      video: `${uri}/caballo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CABRA',
      search_name_es: 'CABRA',
      image: require('../res/image/cabra.png'),
      video: `${uri}/cabra.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHANCHO',
      search_name_es: 'CHANCHO',
      image: require('../res/image/chancho.png'),
      video: `${uri}/chancho.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIERVO',
      search_name_es: 'CIERVO',
      image: require('../res/image/ciervo.png'),
      video: `${uri}/ciervo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCODRILO',
      search_name_es: 'COCODRILO',
      image: require('../res/image/cocodrilo.png'),
      video: `${uri}/cocodrilo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONEJO',
      search_name_es: 'CONEJO',
      image: require('../res/image/conejo.png'),
      video: `${uri}/conejo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEL CAMPO',
      search_name_es: 'DEL CAMPO',
      image: require('../res/image/del-campo.png'),
      video: `${uri}/del-campo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZOOLÓGICO',
      search_name_es: 'ZOOLOGICO',
      image: require('../res/image/el-zoologico.png'),
      video: `${uri}/el-zoologico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ELEFANTE',
      search_name_es: 'ELEFANTE',
      image: require('../res/image/elefante.png'),
      video: `${uri}/elefante.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FOCA',
      search_name_es: 'FOCA',
      image: require('../res/image/foca.png'),
      video: `${uri}/foca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GALLINA',
      search_name_es: 'GALLINA',
      image: require('../res/image/gallina.png'),
      video: `${uri}/gallina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GATO',
      search_name_es: 'GATO',
      image: require('../res/image/gato.png'),
      video: `${uri}/gato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JIRAFA',
      search_name_es: 'JIRAFA',
      image: require('../res/image/jirafa.png'),
      video: `${uri}/jirafa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEÓN',
      search_name_es: 'LEON',
      image: require('../res/image/leon.png'),
      video: `${uri}/leon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLAMA',
      search_name_es: 'LLAMA',
      image: require('../res/image/llama.png'),
      video: `${uri}/llama.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LORO',
      search_name_es: 'LORO',
      image: require('../res/image/loro.png'),
      video: `${uri}/loro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MONO',
      search_name_es: 'MONO',
      image: require('../res/image/mono.png'),
      video: `${uri}/mono.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OSO',
      search_name_es: 'OSO',
      image: require('../res/image/oso.png'),
      video: `${uri}/oso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OVEJA',
      search_name_es: 'OVEJA',
      image: require('../res/image/oveja.png'),
      video: `${uri}/oveja.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PATO',
      search_name_es: 'PATO',
      image: require('../res/image/pato.png'),
      video: `${uri}/pato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RATÓN',
      search_name_es: 'RATON',
      image: require('../res/image/raton.png'),
      video: `${uri}/raton.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAPO',
      search_name_es: 'SAPO',
      image: require('../res/image/sapo.png'),
      video: `${uri}/sapo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TORTUGA',
      search_name_es: 'TORTUGA',
      image: require('../res/image/tortuga.png'),
      video: `${uri}/tortuga.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VACA',
      search_name_es: 'VACA',
      image: require('../res/image/vaca.png'),
      video: `${uri}/vaca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VÍBORA',
      search_name_es: 'VIBORA',
      image: require('../res/image/vibora.png'),
      video: `${uri}/vibora.mp4`,
      downloaded: false,
    },
  ],
});
