export const associations = uri => ({
  name_es: 'ASOCIACIONES DE LA COMUNIDAD SORDA',
  icon: require('../res/icon/asociaciones.png'),
  videos: [
    {
      name_es: 'AAS',
      search_name_es: 'AAS',
      image: require('../res/image/aas.png'),
      video: `${uri}/AAS.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASAM',
      search_name_es: 'ASAM',
      image: require('../res/image/asam.png'),
      video: `${uri}/ASAM.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASO',
      search_name_es: 'ASO ',
      image: require('../res/image/aso.png'),
      video: `${uri}/ASO.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASG',
      search_name_es: 'ASG ',
      image: require('../res/image/asg.png'),
      video: `${uri}/ASG.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASLP',
      search_name_es: 'ASLP',
      image: require('../res/image/aslp.png'),
      video: `${uri}/ASLP.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASCH',
      search_name_es: 'ASCH',
      image: require('../res/image/asch.png'),
      video: `${uri}/ASCH.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASMAR',
      search_name_es: 'ASMAR',
      image: require('../res/image/asmar.png'),
      video: `${uri}/ASMAR.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASM',
      search_name_es: 'ASM',
      image: require('../res/image/asm.png'),
      video: `${uri}/ASM.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MSM',
      search_name_es: 'MSM',
      image: require('../res/image/msm.png'),
      video: `${uri}/MSM.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASAMR',
      search_name_es: 'ASAMR',
      image: require('../res/image/asamr.png'),
      video: `${uri}/ASAMR.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASN',
      search_name_es: 'ASN',
      image: require('../res/image/asn.png'),
      video: `${uri}/ASN.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCS',
      search_name_es: 'OCS',
      image: require('../res/image/ocs.png'),
      video: `${uri}/OCS.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASORSA',
      search_name_es: 'ASORSA',
      image: require('../res/image/asorsa.png'),
      video: `${uri}/ASORSA.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASORSAFE',
      search_name_es: 'ASORSAFE',
      image: require('../res/image/asorsafe.png'),
      video: `${uri}/ASORSAFE.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASSJ',
      search_name_es: 'ASSJ',
      image: require('../res/image/assj.png'),
      video: `${uri}/ASSJ.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ATS',
      search_name_es: 'ATS',
      image: require('../res/image/ats.png'),
      video: `${uri}/ATS.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CSCDSR',
      search_name_es: 'CSCDSR',
      image: require('../res/image/cscdsr.png'),
      video: `${uri}/CSCDSR.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UAS',
      search_name_es: 'UAS',
      image: require('../res/image/uas.png'),
      video: `${uri}/UAS.mp4`,
      downloaded: false,
    },
  ],
});
