export const beach = uri => ({
  name_es: 'PLAYA',
  icon: require('../res/icon/la-playa.png'),
  videos: [
    {
      name_es: 'ARENA',
      search_name_es: 'ARENA',
      image: require('../res/image/arena.png'),
      video: `${uri}/arena.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BALDE',
      search_name_es: 'BALDE',
      image: require('../res/image/balde.png'),
      video: `${uri}/balde.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARCO',
      search_name_es: 'BARCO',
      image: require('../res/image/barco.png'),
      video: `${uri}/barco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GORRO',
      search_name_es: 'GORRO',
      image: require('../res/image/gorro.png'),
      video: `${uri}/gorro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLAYA',
      search_name_es: 'PLAYA',
      image: require('../res/image/la-playa.png'),
      video: `${uri}/la-playa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MALLA DE HOMBRE',
      search_name_es: 'MALLA DE HOMBRE',
      image: require('../res/image/malla-de-hombre.png'),
      video: `${uri}/malla-de-hombre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MALLA DE MUJER',
      search_name_es: 'MALLA DE MUJER',
      image: require('../res/image/malla-de-mujer.png'),
      video: `${uri}/malla-de-mujer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAR',
      search_name_es: 'MAR',
      image: require('../res/image/mar.png'),
      video: `${uri}/mar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PALITA',
      search_name_es: 'PALITA',
      image: require('../res/image/palita.png'),
      video: `${uri}/palita.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOMBRILLA',
      search_name_es: 'SOMBRILLA',
      image: require('../res/image/sombrilla.png'),
      video: `${uri}/sombrilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VACACIONES',
      search_name_es: 'VACACIONES',
      image: require('../res/image/vacaciones.png'),
      video: `${uri}/vacaciones.mp4`,
      downloaded: false,
    },
  ],
});
