export const birthday = uri => ({
  name_es: 'CUMPLEAÑOS',
  icon: require('../res/icon/el-cumpleanos.png'),
  videos: [
    {
      name_es: 'AMIGOS',
      search_name_es: 'AMIGOS',
      image: require('../res/image/amigos.png'),
      video: `${uri}/amigos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (OYENTES)',
      search_name_es: 'APLAUDIR (OYENTES)',
      image: require('../res/image/aplaudir-(oyentes).png'),
      video: `${uri}/aplaudir-(oyentes).mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (SORDOS)',
      search_name_es: 'APLAUDIR (SORDOS)',
      image: require('../res/image/aplaudir-(sordos).png'),
      video: `${uri}/aplaudir-(sordos).mp4`,
      downloaded: false,
    },
    {
      name_es: 'AYUDAR',
      search_name_es: 'AYUDAR',
      image: require('../res/image/ayudar.png'),
      video: `${uri}/ayudar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAILAR',
      search_name_es: 'BAILAR',
      image: require('../res/image/bailar.png'),
      video: `${uri}/bailar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANTAR',
      search_name_es: 'CANTAR',
      image: require('../res/image/cantar.png'),
      video: `${uri}/cantar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONOCER',
      search_name_es: 'CONOCER',
      image: require('../res/image/conocer.png'),
      video: `${uri}/conocer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUIDAR',
      search_name_es: 'CUIDAR',
      image: require('../res/image/cuidar.png'),
      video: `${uri}/cuidar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DISFRAZ',
      search_name_es: 'DISFRAZ',
      image: require('../res/image/disfraz.png'),
      video: `${uri}/disfraz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FILMAR',
      search_name_es: 'FILMAR',
      image: require('../res/image/filmar.png'),
      video: `${uri}/filmar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GLOBOS',
      search_name_es: 'GLOBOS',
      image: require('../res/image/globos.png'),
      video: `${uri}/globos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUGO',
      search_name_es: 'JUGO',
      image: require('../res/image/jugo.png'),
      video: `${uri}/jugo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIESTA DE CUMPLEAÑOS',
      search_name_es: 'FIESTA DE CUMPLEAÑOS',
      image: require('../res/image/la-fiesta-de-cumpleanos.png'),
      video: `${uri}/la-fiesta-de-cumpleanos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÚSICA',
      search_name_es: 'MUSICA',
      image: require('../res/image/musica.png'),
      video: `${uri}/musica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAYASO',
      search_name_es: 'PAYASO',
      image: require('../res/image/payaso.png'),
      video: `${uri}/payaso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REGALAR',
      search_name_es: 'REGALAR',
      image: require('../res/image/regalar.png'),
      video: `${uri}/regalar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RUIDO',
      search_name_es: 'RUIDO',
      image: require('../res/image/ruido.png'),
      video: `${uri}/ruido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SACAR FOTOS',
      search_name_es: 'SACAR FOTOS',
      image: require('../res/image/sacar-fotos.png'),
      video: `${uri}/sacar-fotos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TORTA',
      search_name_es: 'TORTA',
      image: require('../res/image/torta.png'),
      video: `${uri}/torta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VELA',
      search_name_es: 'VELA',
      image: require('../res/image/vela.png'),
      video: `${uri}/vela.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIBRACIÓN',
      search_name_es: 'VIBRACION',
      image: require('../res/image/vibracion.png'),
      video: `${uri}/vibracion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VISITAR',
      search_name_es: 'VISITAR',
      image: require('../res/image/visitar.png'),
      video: `${uri}/visitar.mp4`,
      downloaded: false,
    },
  ],
});
