export const camp = uri => ({
  name_es: 'CAMPAMENTO',
  icon: require('../res/icon/el-campamento.png'),
  videos: [
    {
      name_es: 'ÁRBOL',
      search_name_es: 'ARBOL',
      image: require('../res/image/arbol.png'),
      video: `${uri}/arbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOTE',
      search_name_es: 'BOTE',
      image: require('../res/image/bote.png'),
      video: `${uri}/bote.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARPA',
      search_name_es: 'CARPA',
      image: require('../res/image/carpa.png'),
      video: `${uri}/carpa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIELO',
      search_name_es: 'CIELO',
      image: require('../res/image/cielo.png'),
      video: `${uri}/cielo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPAMENTO',
      search_name_es: 'CAMPAMENTO',
      image: require('../res/image/el-campamento.png'),
      video: `${uri}/el-campamento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FUEGO',
      search_name_es: 'FUEGO',
      image: require('../res/image/fuego.png'),
      video: `${uri}/fuego.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAGO',
      search_name_es: 'LAGO',
      image: require('../res/image/lago.png'),
      video: `${uri}/lago.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LINTERNA',
      search_name_es: 'LINTERNA',
      image: require('../res/image/linterna.png'),
      video: `${uri}/linterna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MARIPOSA',
      search_name_es: 'MARIPOSA',
      image: require('../res/image/mariposa.png'),
      video: `${uri}/mariposa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MONTAÑAS',
      search_name_es: 'MONTAÑAS',
      image: require('../res/image/montanas.png'),
      video: `${uri}/montanas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MOSQUITO',
      search_name_es: 'MOSQUITO',
      image: require('../res/image/mosquito.png'),
      video: `${uri}/mosquito.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PÁJARO',
      search_name_es: 'PAJARO',
      image: require('../res/image/pajaro.png'),
      video: `${uri}/pajaro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PASTO',
      search_name_es: 'PASTO',
      image: require('../res/image/pasto.png'),
      video: `${uri}/pasto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERRO',
      search_name_es: 'PERRO',
      image: require('../res/image/perro.png'),
      video: `${uri}/perro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PESCAR',
      search_name_es: 'PESCAR',
      image: require('../res/image/pescar.png'),
      video: `${uri}/pescar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PEZ',
      search_name_es: 'PEZ',
      image: require('../res/image/pez.png'),
      video: `${uri}/pez.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIEDRA',
      search_name_es: 'PIEDRA',
      image: require('../res/image/piedra.png'),
      video: `${uri}/piedra.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RÍO',
      search_name_es: 'RIO',
      image: require('../res/image/rio.png'),
      video: `${uri}/rio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIERRA',
      search_name_es: 'TIERRA',
      image: require('../res/image/tierra.png'),
      video: `${uri}/tierra.mp4`,
      downloaded: false,
    },
  ],
});
