export const clothes = uri => ({
  name_es: 'ROPA',
  icon: require('../res/icon/la-ropa.png'),
  videos: [
    {
      name_es: 'BOMBACHA',
      search_name_es: 'BOMBACHA',
      image: require('../res/image/bombacha.png'),
      video: `${uri}/bombacha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CALZONCILLO',
      search_name_es: 'CALZONCILLO',
      image: require('../res/image/calzoncillo.png'),
      video: `${uri}/calzoncillo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMBIARSE LA ROPA',
      search_name_es: 'CAMBIARSE LA ROPA',
      image: require('../res/image/cambiarse-la-ropa.png'),
      video: `${uri}/cambiarse-la-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMISA',
      search_name_es: 'CAMISA',
      image: require('../res/image/camisa.png'),
      video: `${uri}/camisa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPERA',
      search_name_es: 'CAMPERA',
      image: require('../res/image/campera.png'),
      video: `${uri}/campera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUARDAR LA ROPA',
      search_name_es: 'GUARDAR LA ROPA',
      image: require('../res/image/guardar-la-ropa.png'),
      video: `${uri}/guardar-la-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEDIAS',
      search_name_es: 'MEDIAS',
      image: require('../res/image/medias.png'),
      video: `${uri}/medias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OJOTAS',
      search_name_es: 'OJOTAS',
      image: require('../res/image/ojotas.png'),
      video: `${uri}/ojotas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PANTALÓN',
      search_name_es: 'PANTALON',
      image: require('../res/image/pantalon.png'),
      video: `${uri}/pantalon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAÑAL',
      search_name_es: 'PAÑAL',
      image: require('../res/image/panal.png'),
      video: `${uri}/panal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POLLERA',
      search_name_es: 'POLLERA',
      image: require('../res/image/pollera.png'),
      video: `${uri}/pollera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PONERSE LA ROPA',
      search_name_es: 'PONERSE LA ROPA',
      image: require('../res/image/ponerse-la-ropa.png'),
      video: `${uri}/ponerse-la-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PULLOVER',
      search_name_es: 'PULLOVER',
      image: require('../res/image/pullover.png'),
      video: `${uri}/pullover.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REMERA',
      search_name_es: 'REMERA',
      image: require('../res/image/remera.png'),
      video: `${uri}/remera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SHORT',
      search_name_es: 'SHORT',
      image: require('../res/image/short.png'),
      video: `${uri}/short.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VESTIDO',
      search_name_es: 'VESTIDO',
      image: require('../res/image/vestido.png'),
      video: `${uri}/vestido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VISTIÉNDOSE',
      search_name_es: 'VISTIENDOSE',
      image: require('../res/image/vistiendose.png'),
      video: `${uri}/vistiendose.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZAPATOS',
      search_name_es: 'ZAPATOS',
      image: require('../res/image/zapatos.png'),
      video: `${uri}/zapatos.mp4`,
      downloaded: false,
    },
  ],
});
