export const colors = uri => ({
  name_es: 'COLORES',
  icon: require('../res/icon/los-colores.png'),
  videos: [
    {
      name_es: 'AMARILLO',
      search_name_es: 'AMARILLO',
      image: require('../res/image/amarillo.png'),
      video: `${uri}/amarillo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AZUL',
      search_name_es: 'AZUL',
      image: require('../res/image/azul.png'),
      video: `${uri}/azul.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BLANCO',
      search_name_es: 'BLANCO',
      image: require('../res/image/blanco.png'),
      video: `${uri}/blanco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CELESTE',
      search_name_es: 'CELESTE',
      image: require('../res/image/celeste.png'),
      video: `${uri}/celeste.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CLARO',
      search_name_es: 'CLARO',
      image: require('../res/image/claro.png'),
      video: `${uri}/claro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRIS',
      search_name_es: 'GRIS',
      image: require('../res/image/gris.png'),
      video: `${uri}/gris.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COLORES',
      search_name_es: 'COLORES',
      image: require('../res/image/los-colores.png'),
      video: `${uri}/los-colores.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MARRÓN',
      search_name_es: 'MARRON',
      image: require('../res/image/marron.png'),
      video: `${uri}/marron.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NARANJA',
      search_name_es: 'NARANJA',
      image: require('../res/image/naranja-color.png'),
      video: `${uri}/naranja-color.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NEGRO',
      search_name_es: 'NEGRO',
      image: require('../res/image/negro.png'),
      video: `${uri}/negro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OSCURO',
      search_name_es: 'OSCURO',
      image: require('../res/image/oscuro.png'),
      video: `${uri}/oscuro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ROJO',
      search_name_es: 'ROJO',
      image: require('../res/image/rojo.png'),
      video: `${uri}/rojo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ROSA',
      search_name_es: 'ROSA',
      image: require('../res/image/rosa.png'),
      video: `${uri}/rosa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VERDE',
      search_name_es: 'VERDE',
      image: require('../res/image/verde.png'),
      video: `${uri}/verde.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIOLETA',
      search_name_es: 'VIOLETA',
      image: require('../res/image/violeta.png'),
      video: `${uri}/violeta.mp4`,
      downloaded: false,
    },
  ],
});
