export const cpcd = uri => ({
  name_es: 'CONVENCIÓN (CPCD)',
  search_name_es: 'CONVENCIÓN (CPCD)',
  icon: require('../res/image/mesa-de-trabajo132.png'),
  videos: [
    {
      name_es: 'ACCESIBILIDAD',
      search_name_es: 'ACCESIBILIDAD',
      image: require('../res/image/accesibilidad.png'),
      video: `${uri}/accesibilidad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ADECUACION',
      search_name_es: 'ADECUACION',
      image: require('../res/image/adecuacion.png'),
      video: `${uri}/adecuacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APOYO',
      search_name_es: 'APOYO',
      image: require('../res/image/apoyo.png'),
      video: `${uri}/apoyo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARTICULOS',
      search_name_es: 'ARTICULOS',
      image: require('../res/image/articulos.png'),
      video: `${uri}/articulos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUTONOMIA',
      search_name_es: 'AUTONOMIA',
      image: require('../res/image/autonomia.png'),
      video: `${uri}/autonomia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRERA',
      search_name_es: 'BARRERA',
      image: require('../res/image/barrera.png'),
      video: `${uri}/barrera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONGRESO',
      search_name_es: 'CONGRESO',
      image: require('../res/image/congreso.png'),
      video: `${uri}/congreso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONVENCION (CPCD)',
      search_name_es: 'CONVENCION (CPCD)',
      image: require('../res/image/mesa-de-trabajo132.png'),
      video: `${uri}/cpcd.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUMPLIMIENTO',
      search_name_es: 'CUMPLIMIENTO',
      image: require('../res/image/cumplimiento.png'),
      video: `${uri}/cumplimiento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEBATE',
      search_name_es: 'DEBATE',
      image: require('../res/image/debate.png'),
      video: `${uri}/debate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DENUNCIAR',
      search_name_es: 'DENUNCIAR',
      image: require('../res/image/denunciar.png'),
      video: `${uri}/denunciar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DERECHOS',
      search_name_es: 'DERECHOS',
      image: require('../res/image/derechos.png'),
      video: `${uri}/derechos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIPUTADOS',
      search_name_es: 'DIPUTADOS',
      image: require('../res/image/diputados.png'),
      video: `${uri}/diputados.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DISCRIMINACION',
      search_name_es: 'DISCRIMINACION',
      image: require('../res/image/discriminacion.png'),
      video: `${uri}/discriminacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ELECCIONES',
      search_name_es: 'ELECCIONES',
      image: require('../res/image/elecciones.png'),
      video: `${uri}/elecciones.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ELEGIR',
      search_name_es: 'ELEGIR',
      image: require('../res/image/elegir.png'),
      video: `${uri}/elegir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EMPODERAMIENTO',
      search_name_es: 'EMPODERAMIENTO',
      image: require('../res/image/empoderamiento.png'),
      video: `${uri}/empoderamiento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENCUESTA',
      search_name_es: 'ENCUESTA',
      image: require('../res/image/encuesta.png'),
      video: `${uri}/encuesta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EQUIDAD',
      search_name_es: 'EQUIDAD',
      image: require('../res/image/equidad.png'),
      video: `${uri}/equidad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTADO',
      search_name_es: 'ESTADO',
      image: require('../res/image/estado.png'),
      video: `${uri}/estado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GOBIERNO',
      search_name_es: 'GOBIERNO',
      image: require('../res/image/gobierno.png'),
      video: `${uri}/gobierno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IGUALDAD',
      search_name_es: 'IGUALDAD',
      image: require('../res/image/igualdad.png'),
      video: `${uri}/igualdad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INCLUSION',
      search_name_es: 'INCLUSION',
      image: require('../res/image/inclusion.png'),
      video: `${uri}/inclusion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INFORMACION',
      search_name_es: 'INFORMACION',
      image: require('../res/image/informacion.png'),
      video: `${uri}/informacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LUCHA',
      search_name_es: 'LUCHA',
      image: require('../res/image/lucha.png'),
      video: `${uri}/lucha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MERCOSUR',
      search_name_es: 'MERCOSUR',
      image: require('../res/image/mercosur.png'),
      video: `${uri}/mercosur.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NECESIDADES',
      search_name_es: 'NECESIDADES',
      image: require('../res/image/necesidades.png'),
      video: `${uri}/necesidades.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OBJETIVO',
      search_name_es: 'OBJETIVO',
      image: require('../res/image/objetivo.png'),
      video: `${uri}/objetivo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARTICIPACION',
      search_name_es: 'PARTICIPACION',
      image: require('../res/image/participacion.png'),
      video: `${uri}/participacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POLITICA',
      search_name_es: 'POLITICA',
      image: require('../res/image/politica.png'),
      video: `${uri}/politica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PROTECCION',
      search_name_es: 'PROTECCION',
      image: require('../res/image/proteccion.png'),
      video: `${uri}/proteccion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RECLAMO',
      search_name_es: 'RECLAMO',
      image: require('../res/image/reclamo.png'),
      video: `${uri}/reclamo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RECONOCIMIENTO',
      search_name_es: 'RECONOCIMIENTO',
      image: require('../res/image/reconocimiento.png'),
      video: `${uri}/reconocimiento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REGLAMENTACION',
      search_name_es: 'REGLAMENTACION',
      image: require('../res/image/reglamentacion.png'),
      video: `${uri}/reglamentacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESPONSABILIDAD',
      search_name_es: 'RESPONSABILIDAD',
      image: require('../res/image/responsabilidad.png'),
      video: `${uri}/responsabilidad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SENADORES',
      search_name_es: 'SENADORES',
      image: require('../res/image/senadores.png'),
      video: `${uri}/senadores.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SERVICIO',
      search_name_es: 'SERVICIO',
      image: require('../res/image/servicio.png'),
      video: `${uri}/servicio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOCIEDAD',
      search_name_es: 'SOCIEDAD',
      image: require('../res/image/sociedad.png'),
      video: `${uri}/sociedad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOMAR CONCIENCIA',
      search_name_es: 'TOMAR CONCIENCIA',
      image: require('../res/image/tomar-conciencia.png'),
      video: `${uri}/tomar-conciencia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VISIBILIZAR',
      search_name_es: 'VISIBILIZAR',
      image: require('../res/image/visibilizar.png'),
      video: `${uri}/visibilizar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOTAR',
      search_name_es: 'VOTAR',
      image: require('../res/image/votar.png'),
      video: `${uri}/votar.mp4`,
      downloaded: false,
    },
  ],
});