export const differences = uri => ({
  name_es: 'DIFERENCIAS',
  icon: require('../res/icon/las-diferencias.png'),
  videos: [
    {
      name_es: 'ABAJO',
      search_name_es: 'ABAJO',
      image: require('../res/image/abajo.png'),
      video: `${uri}/abajo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ADELANTE',
      search_name_es: 'ADELANTE',
      image: require('../res/image/adelante.png'),
      video: `${uri}/adelante.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ADENTRO',
      search_name_es: 'ADENTRO',
      image: require('../res/image/adentro.png'),
      video: `${uri}/adentro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AFUERA',
      search_name_es: 'AFUERA',
      image: require('../res/image/afuera.png'),
      video: `${uri}/afuera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AL LADO',
      search_name_es: 'AL LADO',
      image: require('../res/image/al-lado.png'),
      video: `${uri}/al-lado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALREDEDOR',
      search_name_es: 'ALREDEDOR',
      image: require('../res/image/alrededor.png'),
      video: `${uri}/alrededor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALTO',
      search_name_es: 'ALTO',
      image: require('../res/image/alto.png'),
      video: `${uri}/alto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ANCIANO',
      search_name_es: 'ANCIANO',
      image: require('../res/image/anciano.png'),
      video: `${uri}/anciano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ANTIGUO',
      search_name_es: 'ANTIGUO',
      image: require('../res/image/antiguo.png'),
      video: `${uri}/antiguo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APURADO',
      search_name_es: 'APURADO',
      image: require('../res/image/apurado.png'),
      video: `${uri}/apurado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARRIBA',
      search_name_es: 'ARRIBA',
      image: require('../res/image/arriba.png'),
      video: `${uri}/arriba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ATRÁS',
      search_name_es: 'ATRAS',
      image: require('../res/image/atras.png'),
      video: `${uri}/atras.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAJO',
      search_name_es: 'BAJO',
      image: require('../res/image/bajo.png'),
      video: `${uri}/bajo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BLANDO',
      search_name_es: 'BLANDO',
      image: require('../res/image/blando.png'),
      video: `${uri}/blando.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENO',
      search_name_es: 'BUENO',
      image: require('../res/image/bueno.png'),
      video: `${uri}/bueno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CERCA',
      search_name_es: 'CERCA',
      image: require('../res/image/cerca.png'),
      video: `${uri}/cerca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHICO',
      search_name_es: 'CHICO',
      image: require('../res/image/chico.png'),
      video: `${uri}/chico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORTO',
      search_name_es: 'CORTO',
      image: require('../res/image/corto.png'),
      video: `${uri}/corto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DÉBIL',
      search_name_es: 'DEBIL',
      image: require('../res/image/debil.png'),
      video: `${uri}/debil.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESPACIO',
      search_name_es: 'DESPACIO',
      image: require('../res/image/despacio.png'),
      video: `${uri}/despacio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIFERENTE',
      search_name_es: 'DIFERENTE',
      image: require('../res/image/diferente.png'),
      video: `${uri}/diferente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DURO',
      search_name_es: 'DURO',
      image: require('../res/image/duro.png'),
      video: `${uri}/duro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EDUCADO',
      search_name_es: 'EDUCADO',
      image: require('../res/image/educado.png'),
      video: `${uri}/educado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENTRADA',
      search_name_es: 'ENTRADA',
      image: require('../res/image/entrada.png'),
      video: `${uri}/entrada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FEO',
      search_name_es: 'FEO',
      image: require('../res/image/feo.png'),
      video: `${uri}/feo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FUERTE',
      search_name_es: 'FUERTE',
      image: require('../res/image/fuerte.png'),
      video: `${uri}/fuerte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRANDE',
      search_name_es: 'GRANDE',
      image: require('../res/image/grande.png'),
      video: `${uri}/grande.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IGUAL',
      search_name_es: 'IGUAL',
      image: require('../res/image/igual.png'),
      video: `${uri}/igual.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JOVEN',
      search_name_es: 'JOVEN',
      image: require('../res/image/joven.png'),
      video: `${uri}/joven.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LARGO',
      search_name_es: 'LARGO',
      image: require('../res/image/largo.png'),
      video: `${uri}/largo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIFERENCIAS',
      search_name_es: 'DIFERENCIAS',
      image: require('../res/image/las-diferencias.png'),
      video: `${uri}/las-diferencias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEJOS',
      search_name_es: 'LEJOS',
      image: require('../res/image/lejos.png'),
      video: `${uri}/lejos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LINDO',
      search_name_es: 'LINDO',
      image: require('../res/image/lindo.png'),
      video: `${uri}/lindo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIVIANO',
      search_name_es: 'LIVIANO',
      image: require('../res/image/liviano.png'),
      video: `${uri}/liviano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAL EDUCADO',
      search_name_es: 'MAL EDUCADO',
      image: require('../res/image/mal-educado.png'),
      video: `${uri}/mal-educado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MALO',
      search_name_es: 'MALO',
      image: require('../res/image/malo.png'),
      video: `${uri}/malo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MENTIRA',
      search_name_es: 'MENTIRA',
      image: require('../res/image/mentira.png'),
      video: `${uri}/mentira.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MOJADO',
      search_name_es: 'MOJADO',
      image: require('../res/image/mojado.png'),
      video: `${uri}/mojado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MUCHO',
      search_name_es: 'MUCHO',
      image: require('../res/image/mucho.png'),
      video: `${uri}/mucho.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NUEVO',
      search_name_es: 'NUEVO',
      image: require('../res/image/nuevo.png'),
      video: `${uri}/nuevo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PESADO',
      search_name_es: 'PESADO',
      image: require('../res/image/pesado.png'),
      video: `${uri}/pesado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POCO',
      search_name_es: 'POCO',
      image: require('../res/image/poco.png'),
      video: `${uri}/poco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALIDA',
      search_name_es: 'SALIDA',
      image: require('../res/image/salida.png'),
      video: `${uri}/salida.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SECO',
      search_name_es: 'SECO',
      image: require('../res/image/seco.png'),
      video: `${uri}/seco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOBRE',
      search_name_es: 'SOBRE',
      image: require('../res/image/sobre.png'),
      video: `${uri}/sobre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VERDAD',
      search_name_es: 'VERDAD',
      image: require('../res/image/verdad.png'),
      video: `${uri}/verdad.mp4`,
      downloaded: false,
    },
  ],
});
