export const education = uri => ({
  name_es: 'EDUCACIÓN',
  icon: require('../res/icon/educacion.png'),
  videos: [
    {
      name_es: 'CAPACITACIÓN',
      search_name_es: 'CAPACITACION',
      image: require('../res/image/capacitacion.png'),
      video: `${uri}/capacitacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARRERA',
      search_name_es: 'CARRERA',
      image: require('../res/image/carrera.png'),
      video: `${uri}/carrera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CURSO',
      search_name_es: 'CURSO',
      image: require('../res/image/curso.png'),
      video: `${uri}/curso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EDUCACIÓN',
      search_name_es: 'EDUCACION',
      image: require('../res/image/educacion.png'),
      video: `${uri}/educacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EXAMEN',
      search_name_es: 'EXAMEN',
      image: require('../res/image/examen.png'),
      video: `${uri}/examen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FORMACIÓN',
      search_name_es: 'FORMACION',
      image: require('../res/image/formacion.png'),
      video: `${uri}/formacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JORNADA',
      search_name_es: 'JORNADA',
      image: require('../res/image/jornada.png'),
      video: `${uri}/jornada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOTA',
      search_name_es: 'NOTA',
      image: require('../res/image/nota.png'),
      video: `${uri}/nota.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLANIFICACIÓN',
      search_name_es: 'PLANIFICACION',
      image: require('../res/image/planificacion.png'),
      video: `${uri}/planificacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRIMARIA',
      search_name_es: 'PRIMARIA',
      image: require('../res/image/primaria.png'),
      video: `${uri}/primaria.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SECUNDARIA',
      search_name_es: 'SECUNDARIA',
      image: require('../res/image/secundaria.png'),
      video: `${uri}/secundaria.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TEMA',
      search_name_es: 'TEMA',
      image: require('../res/image/tema.png'),
      video: `${uri}/tema.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TERCIARIA',
      search_name_es: 'TERCIARIA',
      image: require('../res/image/terciaria.png'),
      video: `${uri}/terciaria.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRABAJO PRÁCTICO',
      search_name_es: 'TRABAJO PRACTICO',
      image: require('../res/image/trabajo-practico.png'),
      video: `${uri}/trabajo-practico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UNIVERSIDAD',
      search_name_es: 'UNIVERSIDAD',
      image: require('../res/image/universidad.png'),
      video: `${uri}/universidad.mp4`,
      downloaded: false,
    },
  ],
});
