export const family = uri => ({
  name_es: 'FAMILIA',
  icon: require('../res/icon/la-familia.png'),
  videos: [
    {
      name_es: 'ABRAZAR',
      search_name_es: 'ABRAZAR',
      image: require('../res/image/abrazar.png'),
      video: `${uri}/abrazar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ABUELO',
      search_name_es: 'ABUELO',
      image: require('../res/image/abuelo.png'),
      video: `${uri}/abuelo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMAR',
      search_name_es: 'AMAR',
      image: require('../res/image/amar.png'),
      video: `${uri}/amar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BESAR',
      search_name_es: 'BESAR',
      image: require('../res/image/besar.png'),
      video: `${uri}/besar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CASADOS',
      search_name_es: 'CASADOS',
      image: require('../res/image/casados.png'),
      video: `${uri}/casados.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMUNICAR',
      search_name_es: 'COMUNICAR',
      image: require('../res/image/comunicar.png'),
      video: `${uri}/comunicar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ÉL / ELLA',
      search_name_es: 'EL / ELLA',
      image: require('../res/image/el-ella.png'),
      video: `${uri}/el-ella.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ELLOS / ELLAS',
      search_name_es: 'ELLOS / ELLAS',
      image: require('../res/image/ellos-ellas.png'),
      video: `${uri}/ellos-ellas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRITAR',
      search_name_es: 'GRITAR',
      image: require('../res/image/gritar.png'),
      video: `${uri}/gritar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HABLAR ORAL',
      search_name_es: 'HABLAR ORAL',
      image: require('../res/image/hablar-oral.png'),
      video: `${uri}/hablar-oral.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HERMANO',
      search_name_es: 'HERMANO',
      image: require('../res/image/hermano.png'),
      video: `${uri}/hermano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HIJO',
      search_name_es: 'HIJO',
      image: require('../res/image/hijo.png'),
      video: `${uri}/hijo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUNTOS',
      search_name_es: 'JUNTOS',
      image: require('../res/image/juntos.png'),
      video: `${uri}/juntos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FAMILIA',
      search_name_es: 'FAMILIA',
      image: require('../res/image/la-familia.png'),
      video: `${uri}/la-familia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLAMAR',
      search_name_es: 'LLAMAR',
      image: require('../res/image/llamar.png'),
      video: `${uri}/llamar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAMÁ',
      search_name_es: 'MAMA',
      image: require('../res/image/mama.png'),
      video: `${uri}/mama.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÍO',
      search_name_es: 'MIO',
      image: require('../res/image/mio.png'),
      video: `${uri}/mio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOSOTROS',
      search_name_es: 'NOSOTROS',
      image: require('../res/image/nosotros.png'),
      video: `${uri}/nosotros.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPÁ',
      search_name_es: 'PAPA',
      image: require('../res/image/papa-familiar.png'),
      video: `${uri}/papa-familiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRIMO',
      search_name_es: 'PRIMO',
      image: require('../res/image/primo.png'),
      video: `${uri}/primo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REIR',
      search_name_es: 'REIR',
      image: require('../res/image/reir.png'),
      video: `${uri}/reir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEÑAR',
      search_name_es: 'SEÑAR',
      image: require('../res/image/senar.png'),
      video: `${uri}/senar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEPARADOS',
      search_name_es: 'SEPARADOS',
      image: require('../res/image/separados.png'),
      video: `${uri}/separados.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÍO',
      search_name_es: 'TIO',
      image: require('../res/image/tio.png'),
      video: `${uri}/tio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TUYO',
      search_name_es: 'TUYO',
      image: require('../res/image/tuyo.png'),
      video: `${uri}/tuyo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOS',
      search_name_es: 'VOS',
      image: require('../res/image/vos.png'),
      video: `${uri}/vos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'YO',
      search_name_es: 'YO',
      image: require('../res/image/yo.png'),
      video: `${uri}/yo.mp4`,
      downloaded: false,
    },
  ],
});
