export const feelings = uri => ({
  name_es: 'SENTIMIENTOS',
  icon: require('../res/icon/los-sentimientos.png'),
  videos: [
    {
      name_es: 'ALEGRE',
      search_name_es: 'ALEGRE',
      image: require('../res/image/alegre.png'),
      video: `${uri}/alegre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASUSTADO',
      search_name_es: 'ASUSTADO',
      image: require('../res/image/asustado.png'),
      video: `${uri}/asustado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANSADO',
      search_name_es: 'CANSADO',
      image: require('../res/image/cansado.png'),
      video: `${uri}/cansado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAPRICHOSO',
      search_name_es: 'CAPRICHOSO',
      image: require('../res/image/caprichoso.png'),
      video: `${uri}/caprichoso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONTENTO',
      search_name_es: 'CONTENTO',
      image: require('../res/image/contento.png'),
      video: `${uri}/contento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CULPA',
      search_name_es: 'CULPA',
      image: require('../res/image/culpa.png'),
      video: `${uri}/culpa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENOJADO',
      search_name_es: 'ENOJADO',
      image: require('../res/image/enojado.png'),
      video: `${uri}/enojado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SENTIMIENTOS',
      search_name_es: 'SENTIMIENTOS',
      image: require('../res/image/los-sentimientos.png'),
      video: `${uri}/los-sentimientos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MIEDOSO',
      search_name_es: 'MIEDOSO',
      image: require('../res/image/miedoso.png'),
      video: `${uri}/miedoso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NERVIOSO',
      search_name_es: 'NERVIOSO',
      image: require('../res/image/nervioso.png'),
      video: `${uri}/nervioso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SORPRENDIDO',
      search_name_es: 'SORPRENDIDO',
      image: require('../res/image/sorprendido.png'),
      video: `${uri}/sorprendido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÍMIDO',
      search_name_es: 'TIMIDO',
      image: require('../res/image/timido.png'),
      video: `${uri}/timido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRANQUILO',
      search_name_es: 'TRANQUILO',
      image: require('../res/image/tranquilo.png'),
      video: `${uri}/tranquilo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRISTE',
      search_name_es: 'TRISTE',
      image: require('../res/image/triste.png'),
      video: `${uri}/triste.mp4`,
      downloaded: false,
    },
  ],
});
