export const food = uri => ({
  name_es: 'ALIMENTOS',
  icon: require('../res/icon/los-alimentos.png'),
  videos: [
    {
      name_es: 'ACEITE',
      search_name_es: 'ACEITE',
      image: require('../res/image/aceite.png'),
      video: `${uri}/aceite.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AGUA',
      search_name_es: 'AGUA',
      image: require('../res/image/agua.png'),
      video: `${uri}/agua.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARROZ',
      search_name_es: 'ARROZ',
      image: require('../res/image/arroz.png'),
      video: `${uri}/arroz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASADO',
      search_name_es: 'ASADO',
      image: require('../res/image/asado.png'),
      video: `${uri}/asado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AZÚCAR',
      search_name_es: 'AZUCAR',
      image: require('../res/image/azucar.png'),
      video: `${uri}/azucar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BANANA',
      search_name_es: 'BANANA',
      image: require('../res/image/banana.png'),
      video: `${uri}/banana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARAMELO',
      search_name_es: 'CARAMELO',
      image: require('../res/image/caramelo.png'),
      video: `${uri}/caramelo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARNE',
      search_name_es: 'CARNE',
      image: require('../res/image/carne.png'),
      video: `${uri}/carne.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CEBOLLA',
      search_name_es: 'CEBOLLA',
      image: require('../res/image/cebolla.png'),
      video: `${uri}/cebolla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHOCOLATE',
      search_name_es: 'CHOCOLATE',
      image: require('../res/image/chocolate.png'),
      video: `${uri}/chocolate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EMPANADA',
      search_name_es: 'EMPANADA',
      image: require('../res/image/empanada.png'),
      video: `${uri}/empanada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIDEOS',
      search_name_es: 'FIDEOS',
      image: require('../res/image/fideos.png'),
      video: `${uri}/fideos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRUTA',
      search_name_es: 'FRUTA',
      image: require('../res/image/fruta.png'),
      video: `${uri}/fruta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GALLETITAS',
      search_name_es: 'GALLETITAS',
      image: require('../res/image/galletitas.png'),
      video: `${uri}/galletitas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HAMBURGUESA',
      search_name_es: 'HAMBURGUESA',
      image: require('../res/image/hamburguesa.png'),
      video: `${uri}/hamburguesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HELADO',
      search_name_es: 'HELADO',
      image: require('../res/image/helado.png'),
      video: `${uri}/helado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HUEVO',
      search_name_es: 'HUEVO',
      image: require('../res/image/huevo.png'),
      video: `${uri}/huevo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LECHE',
      search_name_es: 'LECHE',
      image: require('../res/image/leche.png'),
      video: `${uri}/leche.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LECHUGA',
      search_name_es: 'LECHUGA',
      image: require('../res/image/lechuga.png'),
      video: `${uri}/lechuga.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMÓN',
      search_name_es: 'LIMON',
      image: require('../res/image/limon.png'),
      video: `${uri}/limon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALIMENTOS',
      search_name_es: 'ALIMENTOS',
      image: require('../res/image/los-alimentos.png'),
      video: `${uri}/los-alimentos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANTECA',
      search_name_es: 'MANTECA',
      image: require('../res/image/manteca.png'),
      video: `${uri}/manteca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANZANA',
      search_name_es: 'MANZANA',
      image: require('../res/image/manzana.png'),
      video: `${uri}/manzana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MATE',
      search_name_es: 'MATE',
      image: require('../res/image/mate.png'),
      video: `${uri}/mate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MILANESA',
      search_name_es: 'MILANESA',
      image: require('../res/image/milanesa.png'),
      video: `${uri}/milanesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NARANJA',
      search_name_es: 'NARANJA',
      image: require('../res/image/naranja-fruta.png'),
      video: `${uri}/naranja-fruta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAN',
      search_name_es: 'PAN',
      image: require('../res/image/pan.png'),
      video: `${uri}/pan.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPA',
      search_name_es: 'PAPA',
      image: require('../res/image/papa.png'),
      video: `${uri}/papa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPAS FRITAS',
      search_name_es: 'PAPAS FRITAS',
      image: require('../res/image/papas-fritas.png'),
      video: `${uri}/papas-fritas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIZZA',
      search_name_es: 'PIZZA',
      image: require('../res/image/pizza.png'),
      video: `${uri}/pizza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POLLO',
      search_name_es: 'POLLO',
      image: require('../res/image/pollo.png'),
      video: `${uri}/pollo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'QUESO',
      search_name_es: 'QUESO',
      image: require('../res/image/queso.png'),
      video: `${uri}/queso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAL',
      search_name_es: 'SAL',
      image: require('../res/image/sal.png'),
      video: `${uri}/sal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALCHICHA',
      search_name_es: 'SALCHICHA',
      image: require('../res/image/salchicha.png'),
      video: `${uri}/salchicha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANDWICH',
      search_name_es: 'SANDWICH',
      image: require('../res/image/sandwich.png'),
      video: `${uri}/sandwich.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOPA',
      search_name_es: 'SOPA',
      image: require('../res/image/sopa.png'),
      video: `${uri}/sopa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÉ',
      search_name_es: 'TE',
      image: require('../res/image/te.png'),
      video: `${uri}/te.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOMATE',
      search_name_es: 'TOMATE',
      image: require('../res/image/tomate.png'),
      video: `${uri}/tomate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UVA',
      search_name_es: 'UVA',
      image: require('../res/image/uva.png'),
      video: `${uri}/uva.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VERDURA',
      search_name_es: 'VERDURA',
      image: require('../res/image/verdura.png'),
      video: `${uri}/verdura.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZANAHORIA',
      search_name_es: 'ZANAHORIA',
      image: require('../res/image/zanahoria.png'),
      video: `${uri}/zanahoria.mp4`,
      downloaded: false,
    },
  ],
});
