export const games = uri => ({
  name_es: 'JUEGOS',
  icon: require('../res/icon/juegos.png'),
  videos: [
    {
      name_es: 'AJEDREZ',
      search_name_es: 'AJEDREZ',
      image: require('../res/image/ajedrez.png'),
      video: `${uri}/ajedrez.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARTAS',
      search_name_es: 'CARTAS',
      image: require('../res/image/cartas.png'),
      video: `${uri}/cartas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DADOS',
      search_name_es: 'DADOS',
      image: require('../res/image/dados.png'),
      video: `${uri}/dados.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DAMAS',
      search_name_es: 'DAMAS',
      image: require('../res/image/damas.png'),
      video: `${uri}/damas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DOMINÓ',
      search_name_es: 'DOMINO',
      image: require('../res/image/domino.png'),
      video: `${uri}/domino.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUEGOS',
      search_name_es: 'JUEGOS',
      image: require('../res/image/juegos.png'),
      video: `${uri}/juegos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLAYSTATION',
      search_name_es: 'PLAYSTATION',
      image: require('../res/image/play-station.png'),
      video: `${uri}/play-station.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POOL',
      search_name_es: 'POOL',
      image: require('../res/image/pool.png'),
      video: `${uri}/pool.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ROMPECABEZAS',
      search_name_es: 'ROMPECABEZAS',
      image: require('../res/image/rompecabezas.png'),
      video: `${uri}/rompecabezas.mp4`,
      downloaded: false,
    },
  ],
});
