export const geography = uri => ({
  name_es: 'GEOGRAFIA',
  icon: require('../res/icon/geografia.png'),
  videos: [
    {
      name_es: 'AMERICA',
      search_name_es: 'AMERICA',
      image: require('../res/image/america.png'),
      video: `${uri}/america.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMERICA DEL NORTE',
      search_name_es: 'AMERICA DEL NORTE',
      image: require('../res/image/america-norte.png'),
      video: `${uri}/america-norte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMERICA CENTRAL',
      search_name_es: 'AMERICA CENTRAL',
      image: require('../res/image/america-central.png'),
      video: `${uri}/america-central.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LATINOAMERICA',
      search_name_es: 'LATINOAMERICA',
      image: require('../res/image/latinoamerica.png'),
      video: `${uri}/latinoamerica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EUROPA',
      search_name_es: 'EUROPA',
      image: require('../res/image/europa.png'),
      video: `${uri}/europa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AFRICA',
      search_name_es: 'AFRICA',
      image: require('../res/image/africa.png'),
      video: `${uri}/africa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASIA',
      search_name_es: 'ASIA',
      image: require('../res/image/asia.png'),
      video: `${uri}/asia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCEANIA',
      search_name_es: 'OCEANIA',
      image: require('../res/image/oceania.png'),
      video: `${uri}/oceania.mp4`,
      downloaded: false,
    },
  ],
});
