export const hospital = uri => ({
  name_es: 'HOSPITAL Y SALUD',
  icon: require('../res/icon/la-salud.png'),
  videos: [
    {
      name_es: 'ANTEOJOS',
      search_name_es: 'ANTEOJOS',
      image: require('../res/image/anteojos.png'),
      video: `${uri}/anteojos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUDÍFONO',
      search_name_es: 'AUDIFONO',
      image: require('../res/image/audifono.png'),
      video: `${uri}/audifono.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUTORIZACIÓN',
      search_name_es: 'AUTORIZACIÓN',
      image: require('../res/image/autorizacion.png'),
      video: `${uri}/autorizacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CLÍNICA',
      search_name_es: 'CLÍNICA',
      image: require('../res/image/clinica.png'),
      video: `${uri}/clinica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CRECER',
      search_name_es: 'CRECER',
      image: require('../res/image/crecer.png'),
      video: `${uri}/crecer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CURAR',
      search_name_es: 'CURAR',
      image: require('../res/image/curar.png'),
      video: `${uri}/curar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DOLOR',
      search_name_es: 'DOLOR',
      image: require('../res/image/dolor.png'),
      video: `${uri}/dolor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOSPITAL',
      search_name_es: 'HOSPITAL',
      image: require('../res/image/el-hospital.png'),
      video: `${uri}/el-hospital.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EMBARAZO',
      search_name_es: 'EMBARAZO',
      image: require('../res/image/embarazo.png'),
      video: `${uri}/embarazo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENFERMEDADES',
      search_name_es: 'ENFERMEDADES',
      image: require('../res/image/enfermedades.png'),
      video: `${uri}/enfermedades.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENFERMERA',
      search_name_es: 'ENFERMERA',
      image: require('../res/image/enfermera.png'),
      video: `${uri}/enfermera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENFERMO',
      search_name_es: 'ENFERMO',
      image: require('../res/image/enfermo.png'),
      video: `${uri}/enfermo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIEBRE',
      search_name_es: 'FIEBRE',
      image: require('../res/image/fiebre.png'),
      video: `${uri}/fiebre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FONOAUDIÓLOGA',
      search_name_es: 'FONOAUDIOLOGA',
      image: require('../res/image/fonoaudiologa.png'),
      video: `${uri}/fonoaudiologa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUARDIA',
      search_name_es: 'GUARDIA',
      image: require('../res/image/guardia.png'),
      video: `${uri}/guardia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HACER ANÁLISIS',
      search_name_es: 'HACER ANALISIS',
      image: require('../res/image/hacer-analisis.png'),
      video: `${uri}/hacer-analisis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IMPLANTE COCLEAR',
      search_name_es: 'IMPLANTE COCLEAR',
      image: require('../res/image/implante-coclear.png'),
      video: `${uri}/implante-coclear.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INTERNACIÓN',
      search_name_es: 'INTERNACIÓN',
      image: require('../res/image/internacion.png'),
      video: `${uri}/internacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INYECCIÓN',
      search_name_es: 'INYECCION',
      image: require('../res/image/inyeccion.png'),
      video: `${uri}/inyeccion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALUD',
      search_name_es: 'SALUD',
      image: require('../res/image/la-salud.png'),
      video: `${uri}/la-salud.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LASTIMADO',
      search_name_es: 'LASTIMADO',
      image: require('../res/image/lastimado.png'),
      video: `${uri}/lastimado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAREADO',
      search_name_es: 'MAREADO',
      image: require('../res/image/mareado.png'),
      video: `${uri}/mareado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO',
      search_name_es: 'MEDICO',
      image: require('../res/image/medico.png'),
      video: `${uri}/medico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO CIRUJANO',
      search_name_es: 'MÉDICO CIRUJANO',
      image: require('../res/image/medico-cirujano.png'),
      video: `${uri}/medico-cirujano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO GINECÓLOGO',
      search_name_es: 'MÉDICO GINECÓLOGO',
      image: require('../res/image/medico-ginecologo.png'),
      video: `${uri}/medico-ginecologo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO ODONTÓLOGO',
      search_name_es: 'MÉDICO ODONTÓLOGO',
      image: require('../res/image/medico-odontologo.png'),
      video: `${uri}/medico-odontologo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO OFTALMÓLOGO',
      search_name_es: 'MÉDICO OFTALMÓLOGO',
      image: require('../res/image/medico-oftalmologo.png'),
      video: `${uri}/medico-oftalmologo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÉDICO TRUMATÓLOGO',
      search_name_es: 'MÉDICO TRUMATÓLOGO',
      image: require('../res/image/medico-traumatologo.png'),
      video: `${uri}/medico-traumatologo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEJORAR',
      search_name_es: 'MEJORAR',
      image: require('../res/image/mejorar.png'),
      video: `${uri}/mejorar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OBRA SOCIAL',
      search_name_es: 'OBRA SOCIAL',
      image: require('../res/image/obra-social.png'),
      video: `${uri}/obra-social.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRIVADA',
      search_name_es: 'PRIVADA',
      image: require('../res/image/privada.png'),
      video: `${uri}/privada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PSICÓLOGO',
      search_name_es: 'PSICOLOGO',
      image: require('../res/image/psicologo.png'),
      video: `${uri}/psicologo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PÚBLICA',
      search_name_es: 'PÚBLICA',
      image: require('../res/image/publica.png'),
      video: `${uri}/publica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REMEDIO',
      search_name_es: 'REMEDIO',
      image: require('../res/image/remedio.png'),
      video: `${uri}/remedio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESONANCIA',
      search_name_es: 'RESONANCIA',
      image: require('../res/image/resonancia.png'),
      video: `${uri}/resonancia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESPIRAR',
      search_name_es: 'RESPIRAR',
      image: require('../res/image/respirar.png'),
      video: `${uri}/respirar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REVISAR',
      search_name_es: 'REVISAR',
      image: require('../res/image/revisar.png'),
      video: `${uri}/revisar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SACAR RADIOGRAFÍA',
      search_name_es: 'SACAR RADIOGRAFIA',
      image: require('../res/image/sacar-radiografia.png'),
      video: `${uri}/sacar-radiografia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANO',
      search_name_es: 'SANO',
      image: require('../res/image/sano.png'),
      video: `${uri}/sano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TERMÓMETRO',
      search_name_es: 'TERMOMETRO',
      image: require('../res/image/termometro.png'),
      video: `${uri}/termometro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TEST HIV',
      search_name_es: 'TEST HIV',
      image: require('../res/image/test-hiv.png'),
      video: `${uri}/test-hiv.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRATAMIENTO',
      search_name_es: 'TRATAMIENTO',
      image: require('../res/image/tratamiento.png'),
      video: `${uri}/tratamiento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOMITAR',
      search_name_es: 'VOMITAR',
      image: require('../res/image/vomitar.png'),
      video: `${uri}/vomitar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'YESO',
      search_name_es: 'YESO',
      image: require('../res/image/yeso.png'),
      video: `${uri}/yeso.mp4`,
      downloaded: false,
    },
  ],
});
