export const house = uri => ({
  name_es: 'CASA',
  icon: require('../res/icon/la-casa.png'),
  videos: [
    {
      name_es: 'ACOSTARSE',
      search_name_es: 'ACOSTARSE',
      image: require('../res/image/acostarse.png'),
      video: `${uri}/acostarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMOHADA',
      search_name_es: 'ALMOHADA',
      image: require('../res/image/almohada.png'),
      video: `${uri}/almohada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAÑAR',
      search_name_es: 'BAÑAR',
      image: require('../res/image/banar.png'),
      video: `${uri}/banar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRER',
      search_name_es: 'BARRER',
      image: require('../res/image/barrer.png'),
      video: `${uri}/barrer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BEBÉ',
      search_name_es: 'BEBE',
      image: require('../res/image/bebe.png'),
      video: `${uri}/bebe.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMA',
      search_name_es: 'CAMA',
      image: require('../res/image/cama.png'),
      video: `${uri}/cama.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANILLA',
      search_name_es: 'CANILLA',
      image: require('../res/image/canilla.png'),
      video: `${uri}/canilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CEPILLAR LOS DIENTES',
      search_name_es: 'CEPILLAR LOS DIENTES',
      image: require('../res/image/cepillar-los-dientes.png'),
      video: `${uri}/cepillar-los-dientes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINA',
      search_name_es: 'COCINA',
      image: require('../res/image/cocina.png'),
      video: `${uri}/cocina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINAR',
      search_name_es: 'COCINAR',
      image: require('../res/image/cocinar.png'),
      video: `${uri}/cocinar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONTROL REMOTO',
      search_name_es: 'CONTROL REMOTO',
      image: require('../res/image/control-remoto.png'),
      video: `${uri}/control-remoto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONVERSAR',
      search_name_es: 'CONVERSAR',
      image: require('../res/image/conservar.png'),
      video: `${uri}/conservar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUCHARA',
      search_name_es: 'CUCHARA',
      image: require('../res/image/cuchara.png'),
      video: `${uri}/cuchara.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUCHILLO',
      search_name_es: 'CUCHILLO',
      image: require('../res/image/cuchillo.png'),
      video: `${uri}/cuchillo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIARIO',
      search_name_es: 'DIARIO',
      image: require('../res/image/diario.png'),
      video: `${uri}/diario.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DORMIR',
      search_name_es: 'DORMIR',
      image: require('../res/image/dormir.png'),
      video: `${uri}/dormir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DUCHA',
      search_name_es: 'DUCHA',
      image: require('../res/image/ducha.png'),
      video: `${uri}/ducha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DULCE',
      search_name_es: 'DULCE',
      image: require('../res/image/dulce.png'),
      video: `${uri}/dulce.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAÑO',
      search_name_es: 'BAÑO',
      image: require('../res/image/el-bano.png'),
      video: `${uri}/el-bano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DORMITORIO',
      search_name_es: 'DORMITORIO',
      image: require('../res/image/el-dormitorio.png'),
      video: `${uri}/el-dormitorio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESPEJO',
      search_name_es: 'ESPEJO',
      image: require('../res/image/espejo.png'),
      video: `${uri}/espejo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTÁ CALIENTE',
      search_name_es: 'ESTA CALIENTE',
      image: require('../res/image/esta-caliente.png'),
      video: `${uri}/esta-caliente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRAZADA',
      search_name_es: 'FRAZADA',
      image: require('../res/image/frazada.png'),
      video: `${uri}/frazada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HELADERA',
      search_name_es: 'HELADERA',
      image: require('../res/image/heladera.png'),
      video: `${uri}/heladera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HORNO',
      search_name_es: 'HORNO',
      image: require('../res/image/horno.png'),
      video: `${uri}/horno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INODORO',
      search_name_es: 'INODORO',
      image: require('../res/image/inodoro.png'),
      video: `${uri}/inodoro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JABÓN',
      search_name_es: 'JABON',
      image: require('../res/image/jabon.png'),
      video: `${uri}/jabon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUGUETES',
      search_name_es: 'JUGUETES',
      image: require('../res/image/juguetes.png'),
      video: `${uri}/juguetes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CASA',
      search_name_es: 'CASA',
      image: require('../res/image/la-casa.png'),
      video: `${uri}/la-casa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINA',
      search_name_es: 'COCINA',
      image: require('../res/image/la-cocina.png'),
      video: `${uri}/la-cocina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR LOS PLATOS',
      search_name_es: 'LAVAR LOS PLATOS',
      image: require('../res/image/lavar-los-platos.png'),
      video: `${uri}/lavar-los-platos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR ROPA',
      search_name_es: 'LAVAR ROPA',
      image: require('../res/image/lavar-ropa.png'),
      video: `${uri}/lavar-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVARROPAS',
      search_name_es: 'LAVARROPAS',
      image: require('../res/image/lavarropas.png'),
      video: `${uri}/lavarropas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVARSE LAS MANOS',
      search_name_es: 'LAVARSE LAS MANOS',
      image: require('../res/image/lavarse-las-manos.png'),
      video: `${uri}/lavarse-las-manos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEER',
      search_name_es: 'LEER',
      image: require('../res/image/leer.png'),
      video: `${uri}/leer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEVANTARSE',
      search_name_es: 'LEVANTARSE',
      image: require('../res/image/levantarse.png'),
      video: `${uri}/levantarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIBRO DE CUENTOS',
      search_name_es: 'LIBRO DE CUENTOS',
      image: require('../res/image/libro-de-cuentos.png'),
      video: `${uri}/libro-de-cuentos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMPIAR',
      search_name_es: 'LIMPIAR',
      image: require('../res/image/limpiar.png'),
      video: `${uri}/limpiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMPIO',
      search_name_es: 'LIMPIO',
      image: require('../res/image/limpio.png'),
      video: `${uri}/limpio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIVING',
      search_name_es: 'LIVING',
      image: require('../res/image/living.png'),
      video: `${uri}/living.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLAVE',
      search_name_es: 'LLAVE',
      image: require('../res/image/llave.png'),
      video: `${uri}/llave.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLORAR',
      search_name_es: 'LLORAR',
      image: require('../res/image/llorar.png'),
      video: `${uri}/llorar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ME GUSTA',
      search_name_es: 'ME GUSTA',
      image: require('../res/image/me-gusta.png'),
      video: `${uri}/me-gusta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MESA',
      search_name_es: 'MESA',
      image: require('../res/image/mesa.png'),
      video: `${uri}/mesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MESITA DE LUZ',
      search_name_es: 'MESITA DE LUZ',
      image: require('../res/image/mesita-de-luz.png'),
      video: `${uri}/mesita-de-luz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MUEBLES',
      search_name_es: 'MUEBLES',
      image: require('../res/image/muebles.png'),
      video: `${uri}/muebles.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO ME GUSTA',
      search_name_es: 'NO ME GUSTA',
      image: require('../res/image/no-me-gusta.png'),
      video: `${uri}/no-me-gusta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCUPADO',
      search_name_es: 'OCUPADO',
      image: require('../res/image/ocupado.png'),
      video: `${uri}/ocupado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPEL HIGIÉNICO',
      search_name_es: 'PAPEL HIGIENICO',
      image: require('../res/image/papel-higienico.png'),
      video: `${uri}/papel-higienico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAVA',
      search_name_es: 'PAVA',
      image: require('../res/image/pava.png'),
      video: `${uri}/pava.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PEINAR',
      search_name_es: 'PEINAR',
      image: require('../res/image/peinar.png'),
      video: `${uri}/peinar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLACARD',
      search_name_es: 'PLACARD',
      image: require('../res/image/placard.png'),
      video: `${uri}/placard.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLANCHAR',
      search_name_es: 'PLANCHAR',
      image: require('../res/image/planchar.png'),
      video: `${uri}/planchar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLATO',
      search_name_es: 'PLATO',
      image: require('../res/image/plato.png'),
      video: `${uri}/plato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PUERTA',
      search_name_es: 'PUERTA',
      image: require('../res/image/puerta.png'),
      video: `${uri}/puerta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RICO',
      search_name_es: 'RICO',
      image: require('../res/image/rico.png'),
      video: `${uri}/rico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ROPA',
      search_name_es: 'ROPA',
      image: require('../res/image/ropa.png'),
      video: `${uri}/ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SÁBANA',
      search_name_es: 'SABANA',
      image: require('../res/image/sabana.png'),
      video: `${uri}/sabana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALADO',
      search_name_es: 'SALADO',
      image: require('../res/image/salado.png'),
      video: `${uri}/salado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SENTARSE',
      search_name_es: 'SENTARSE',
      image: require('../res/image/sentarse.png'),
      video: `${uri}/sentarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SERVILLETA',
      search_name_es: 'SERVILLETA',
      image: require('../res/image/servilleta.png'),
      video: `${uri}/servilleta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SILLA',
      search_name_es: 'SILLA',
      image: require('../res/image/silla.png'),
      video: `${uri}/silla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOFÁ',
      search_name_es: 'SOFA',
      image: require('../res/image/sofa.png'),
      video: `${uri}/sofa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUCIO',
      search_name_es: 'SUCIO',
      image: require('../res/image/sucio.png'),
      video: `${uri}/sucio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TACHO DE BASURA',
      search_name_es: 'TACHO DE BASURA',
      image: require('../res/image/tacho-de-basura.png'),
      video: `${uri}/tacho-de-basura.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TELEVISOR',
      search_name_es: 'TELEVISOR',
      image: require('../res/image/televisor.png'),
      video: `${uri}/televisor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENEDOR',
      search_name_es: 'TENEDOR',
      image: require('../res/image/tenedor.png'),
      video: `${uri}/tenedor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER HAMBRE',
      search_name_es: 'TENER HAMBRE',
      image: require('../res/image/tener-hambre.png'),
      video: `${uri}/tener-hambre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER SED',
      search_name_es: 'TENER SED',
      image: require('../res/image/tener-sed.png'),
      video: `${uri}/tener-sed.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER SUEÑO',
      search_name_es: 'TENER SUEÑO',
      image: require('../res/image/tener-sueno.png'),
      video: `${uri}/tener-sueno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOALLA',
      search_name_es: 'TOALLA',
      image: require('../res/image/toalla.png'),
      video: `${uri}/toalla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOCAR TIMBRE',
      search_name_es: 'TOCAR TIMBRE',
      image: require('../res/image/tocar-timbre.png'),
      video: `${uri}/tocar-timbre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VASO',
      search_name_es: 'VASO',
      image: require('../res/image/vaso.png'),
      video: `${uri}/vaso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENTANA',
      search_name_es: 'VENTANA',
      image: require('../res/image/ventana.png'),
      video: `${uri}/ventana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENTILADOR',
      search_name_es: 'VENTILADOR',
      image: require('../res/image/ventilador.png'),
      video: `${uri}/ventilador.mp4`,
      downloaded: false,
    },
  ],
});
