export const introducing = uri => ({
  name_es: 'PRESENTÁNDONOS',
  icon: require('../res/icon/presentandonos.png'),
  videos: [
    {
      name_es: '¿CÓMO ESTÁS?',
      search_name_es: '¿COMO ESTAS?',
      image: require('../res/image/como-estas.png'),
      video: `${uri}/como-estas.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CÓMO?',
      search_name_es: '¿COMO?',
      image: require('../res/image/como.png'),
      video: `${uri}/como.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁL?',
      search_name_es: '¿CUAL?',
      image: require('../res/image/cual.png'),
      video: `${uri}/cual.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁNDO?',
      search_name_es: '¿CUANDO?',
      image: require('../res/image/cuando.png'),
      video: `${uri}/cuando.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁNTO?',
      search_name_es: '¿CUANTO?',
      image: require('../res/image/cuanto.png'),
      video: `${uri}/cuanto.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁNTOS AÑOS TENÉS?',
      search_name_es: '¿CUANTOS AÑOS TENES?',
      image: require('../res/image/cuantos-anos-tenes.png'),
      video: `${uri}/cuantos-anos-tenes.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿DÓNDE?',
      search_name_es: '¿DONDE?',
      image: require('../res/image/donde.png'),
      video: `${uri}/donde.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿PARA QUÉ?',
      search_name_es: '¿PARA QUE?',
      image: require('../res/image/para-que.png'),
      video: `${uri}/para-que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿POR QUÉ?',
      search_name_es: '¿POR QUE?',
      image: require('../res/image/por-que.png'),
      video: `${uri}/por-que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUÉ DICE?',
      search_name_es: '¿QUE DICE?',
      image: require('../res/image/que-dice.png'),
      video: `${uri}/que-dice.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUÉ?',
      search_name_es: '¿QUE?',
      image: require('../res/image/que.png'),
      video: `${uri}/que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUIÉN?',
      search_name_es: '¿QUIEN?',
      image: require('../res/image/quien.png'),
      video: `${uri}/quien.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APELLIDO',
      search_name_es: 'APELLIDO',
      image: require('../res/image/apellido.png'),
      video: `${uri}/apellido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BASTA',
      search_name_es: 'BASTA',
      image: require('../res/image/basta.png'),
      video: `${uri}/basta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIEN',
      search_name_es: 'BIEN',
      image: require('../res/image/bien.png'),
      video: `${uri}/bien.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENAS NOCHES',
      search_name_es: 'BUENAS NOCHES',
      image: require('../res/image/buenas-noches.png'),
      video: `${uri}/buenas-noches.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENAS TARDES',
      search_name_es: 'BUENAS TARDES',
      image: require('../res/image/buenas-tardes.png'),
      video: `${uri}/buenas-tardes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENOS DÍAS',
      search_name_es: 'BUENOS DIAS',
      image: require('../res/image/buenos-dias.png'),
      video: `${uri}/buenos-dias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHAU',
      search_name_es: 'CHAU',
      image: require('../res/image/chau.png'),
      video: `${uri}/chau.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DE NADA',
      search_name_es: 'DE NADA',
      image: require('../res/image/de-nada.png'),
      video: `${uri}/de-nada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRACIAS',
      search_name_es: 'GRACIAS',
      image: require('../res/image/gracias.png'),
      video: `${uri}/gracias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOLA',
      search_name_es: 'HOLA',
      image: require('../res/image/hola.png'),
      video: `${uri}/hola.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAL',
      search_name_es: 'MAL',
      image: require('../res/image/mal.png'),
      video: `${uri}/mal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO',
      search_name_es: 'NO',
      image: require('../res/image/no.png'),
      video: `${uri}/no.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOMBRE',
      search_name_es: 'NOMBRE',
      image: require('../res/image/nombre.png'),
      video: `${uri}/nombre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OYENTE',
      search_name_es: 'OYENTE',
      image: require('../res/image/oyente.png'),
      video: `${uri}/oyente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERDÓN',
      search_name_es: 'PERDON',
      image: require('../res/image/perdon.png'),
      video: `${uri}/perdon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERMISO',
      search_name_es: 'PERMISO',
      image: require('../res/image/permiso.png'),
      video: `${uri}/permiso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POR EJEMPLO',
      search_name_es: 'POR EJEMPLO',
      image: require('../res/image/por-ejemplo.png'),
      video: `${uri}/por-ejemplo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POR FAVOR',
      search_name_es: 'POR FAVOR',
      image: require('../res/image/por-favor.png'),
      video: `${uri}/por-favor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRESENTÁNDONOS',
      search_name_es: 'PRESENTANDONOS',
      image: require('../res/image/presentandonos.png'),
      video: `${uri}/presentandonos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALUDOS',
      search_name_es: 'SALUDOS',
      image: require('../res/image/saludos.png'),
      video: `${uri}/saludos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEÑA PERSONAL',
      search_name_es: 'SEÑA PERSONAL',
      image: require('../res/image/sena-personal.png'),
      video: `${uri}/sena-personal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SI',
      search_name_es: 'SI',
      image: require('../res/image/si.png'),
      video: `${uri}/si.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SORDO',
      search_name_es: 'SORDO',
      image: require('../res/image/sordo.png'),
      video: `${uri}/sordo.mp4`,
      downloaded: false,
    },
  ],
});
