export const numbers = uri => ({
  name_es: 'NÚMEROS',
  icon: require('../res/icon/los-numeros.png'),
  videos: [
    {
      name_es: 'NÚMEROS',
      search_name_es: 'NUMEROS',
      image: require('../res/image/los-numeros.png'),
      video: `${uri}/los-numeros.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UNO',
      search_name_es: 'UNO',
      image: require('../res/image/uno.png'),
      video: `${uri}/uno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DOS',
      search_name_es: 'DOS',
      image: require('../res/image/dos.png'),
      video: `${uri}/dos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRES',
      search_name_es: 'TRES',
      image: require('../res/image/tres.png'),
      video: `${uri}/tres.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUATRO',
      search_name_es: 'CUATRO',
      image: require('../res/image/cuatro.png'),
      video: `${uri}/cuatro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CINCO',
      search_name_es: 'CINCO',
      image: require('../res/image/cinco.png'),
      video: `${uri}/cinco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEIS',
      search_name_es: 'SEIS',
      image: require('../res/image/seis.png'),
      video: `${uri}/seis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SIETE',
      search_name_es: 'SIETE',
      image: require('../res/image/siete.png'),
      video: `${uri}/siete.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCHO',
      search_name_es: 'OCHO',
      image: require('../res/image/ocho.png'),
      video: `${uri}/ocho.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NUEVE',
      search_name_es: 'NUEVE',
      image: require('../res/image/nueve.png'),
      video: `${uri}/nueve.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIEZ',
      search_name_es: 'DIEZ',
      image: require('../res/image/diez.png'),
      video: `${uri}/diez.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ONCE',
      search_name_es: 'ONCE',
      image: require('../res/image/once.png'),
      video: `${uri}/once.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DOCE',
      search_name_es: 'DOCE',
      image: require('../res/image/doce.png'),
      video: `${uri}/doce.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRECE',
      search_name_es: 'TRECE',
      image: require('../res/image/trece.png'),
      video: `${uri}/trece.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CATORCE',
      search_name_es: 'CATORCE',
      image: require('../res/image/catorce.png'),
      video: `${uri}/catorce.mp4`,
      downloaded: false,
    },
    {
      name_es: 'QUINCE',
      search_name_es: 'QUINCE',
      image: require('../res/image/quince.png'),
      video: `${uri}/quince.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIECISEIS',
      search_name_es: 'DIECISEIS',
      image: require('../res/image/dieciseis.png'),
      video: `${uri}/dieciseis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIECISIETE',
      search_name_es: 'DIECISIETE',
      image: require('../res/image/diecisiete.png'),
      video: `${uri}/diecisiete.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIECIOCHO',
      search_name_es: 'DIECIOCHO',
      image: require('../res/image/dieciocho.png'),
      video: `${uri}/dieciocho.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIECINUEVE',
      search_name_es: 'DIECINUEVE',
      image: require('../res/image/diecinueve.png'),
      video: `${uri}/diecinueve.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VEINTE',
      search_name_es: 'VEINTE',
      image: require('../res/image/veinte.png'),
      video: `${uri}/veinte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TREINTA',
      search_name_es: 'TREINTA',
      image: require('../res/image/treinta.png'),
      video: `${uri}/treinta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUARENTA',
      search_name_es: 'CUARENTA',
      image: require('../res/image/cuarenta.png'),
      video: `${uri}/cuarenta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CINCUENTA',
      search_name_es: 'CINCUENTA',
      image: require('../res/image/cincuenta.png'),
      video: `${uri}/cincuenta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SESENTA',
      search_name_es: 'SESENTA',
      image: require('../res/image/sesenta.png'),
      video: `${uri}/sesenta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SETENTA',
      search_name_es: 'SETENTA',
      image: require('../res/image/setenta.png'),
      video: `${uri}/setenta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCHENTA',
      search_name_es: 'OCHENTA',
      image: require('../res/image/ochenta.png'),
      video: `${uri}/ochenta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOVENTA',
      search_name_es: 'NOVENTA',
      image: require('../res/image/noventa.png'),
      video: `${uri}/noventa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIEN',
      search_name_es: 'CIEN',
      image: require('../res/image/cien.png'),
      video: `${uri}/cien.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MIL',
      search_name_es: 'MIL',
      image: require('../res/image/mil.png'),
      video: `${uri}/mil.mp4`,
      downloaded: false,
    },
  ],
});
