export const sports = uri => ({
  name_es: 'DEPORTES',
  icon: require('../res/icon/deportes.png'),
  videos: [
    {
      name_es: 'ARTES MARCIALES',
      search_name_es: 'ARTES MARCIALES',
      image: require('../res/image/artes-marciales.png'),
      video: `${uri}/artes-marciales.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ATLETISMO',
      search_name_es: 'ATLETISMO',
      image: require('../res/image/atletismo.png'),
      video: `${uri}/atletismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUTOMOVILISMO',
      search_name_es: 'AUTOMOVILISMO',
      image: require('../res/image/automovilismo.png'),
      video: `${uri}/automovilismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BÁSQUET',
      search_name_es: 'BÁSQUET',
      image: require('../res/image/basquet.png'),
      video: `${uri}/basquet.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOWLING',
      search_name_es: 'BOWLING',
      image: require('../res/image/bowling.png'),
      video: `${uri}/bowling.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPEONATO',
      search_name_es: 'CAMPEONATO',
      image: require('../res/image/campeonato.png'),
      video: `${uri}/campeonato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CICLISMO',
      search_name_es: 'CICLISMO',
      image: require('../res/image/ciclismo.png'),
      video: `${uri}/ciclismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEPORTES',
      search_name_es: 'DEPORTES',
      image: require('../res/image/deportes.png'),
      video: `${uri}/deportes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GOLF',
      search_name_es: 'GOLF',
      image: require('../res/image/golf.png'),
      video: `${uri}/golf.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HANDBOL',
      search_name_es: 'HANDBOL',
      image: require('../res/image/handbol.png'),
      video: `${uri}/handbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOCKEY',
      search_name_es: 'HOCKEY',
      image: require('../res/image/hockey.png'),
      video: `${uri}/hockey.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NATACIÓN',
      search_name_es: 'NATACIÓN',
      image: require('../res/image/natacion.png'),
      video: `${uri}/natacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OLIMPIADAS',
      search_name_es: 'OLIMPIADAS',
      image: require('../res/image/olimpiadas.png'),
      video: `${uri}/olimpiadas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPI FÚTBOL',
      search_name_es: 'PAPI FÚTBOL',
      image: require('../res/image/papi-futbol.png'),
      video: `${uri}/papi-futbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PATINES',
      search_name_es: 'PATINES',
      image: require('../res/image/patines.png'),
      video: `${uri}/patines.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RUGBY',
      search_name_es: 'RUGBY',
      image: require('../res/image/rugby.png'),
      video: `${uri}/rugby.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SURF',
      search_name_es: 'SURF',
      image: require('../res/image/surf.png'),
      video: `${uri}/surf.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENIS',
      search_name_es: 'TENIS',
      image: require('../res/image/tenis.png'),
      video: `${uri}/tenis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOLEIBOL',
      search_name_es: 'VOLEIBOL',
      image: require('../res/image/voleibol.png'),
      video: `${uri}/voleibol.mp4`,
      downloaded: false,
    },
  ],
});
