export const technology = uri => ({
  name_es: 'TECNOLOGÍA',
  icon: require('../res/icon/la-tecnologia.png'),
  videos: [
    {
      name_es: 'ADJUNTAR',
      search_name_es: 'ADJUNTAR',
      image: require('../res/image/adjuntar.png'),
      video: `${uri}/adjuntar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BLOG',
      search_name_es: 'BLOG',
      image: require('../res/image/blog.png'),
      video: `${uri}/blog.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CALCULADORA',
      search_name_es: 'CALCULADORA',
      image: require('../res/image/calculadora.png'),
      video: `${uri}/calculadora.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CELULAR',
      search_name_es: 'CELULAR',
      image: require('../res/image/celular.png'),
      video: `${uri}/celular.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMPUTADORA',
      search_name_es: 'COMPUTADORA',
      image: require('../res/image/computadora.png'),
      video: `${uri}/computadora.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DRIVE',
      search_name_es: 'DRIVE',
      image: require('../res/image/drive.png'),
      video: `${uri}/drive.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DVD',
      search_name_es: 'DVD',
      image: require('../res/image/dvd.png'),
      video: `${uri}/dvd.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EMAIL',
      search_name_es: 'EMAIL',
      image: require('../res/image/email.png'),
      video: `${uri}/email.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESCÁNER',
      search_name_es: 'ESCÁNER',
      image: require('../res/image/escanear.png'),
      video: `${uri}/escaner.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FACEBOOK',
      search_name_es: 'FACEBOOK',
      image: require('../res/image/facebook.png'),
      video: `${uri}/facebook.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FOTOCOPIAR',
      search_name_es: 'FOTOCOPIAR',
      image: require('../res/image/fotocopiar.png'),
      video: `${uri}/fotocopiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GOOGLE',
      search_name_es: 'GOOGLE',
      image: require('../res/image/google.png'),
      video: `${uri}/google.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IMPRESORA',
      search_name_es: 'IMPRESORA',
      image: require('../res/image/impresora.png'),
      video: `${uri}/impresora.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INSTAGRAM',
      search_name_es: 'INSTAGRAM',
      image: require('../res/image/instagram.png'),
      video: `${uri}/instagram.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INTERNET',
      search_name_es: 'INTERNET',
      image: require('../res/image/internet.png'),
      video: `${uri}/internet.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TECNOLOGÍA',
      search_name_es: 'TECNOLOGIA',
      image: require('../res/image/la-tecnologia.png'),
      video: `${uri}/la-tecnologia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEMORIA',
      search_name_es: 'MEMORIA',
      image: require('../res/image/memoria.png'),
      video: `${uri}/memoria.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MOUSE',
      search_name_es: 'MOUSE',
      image: require('../res/image/mouse.png'),
      video: `${uri}/mouse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NETFLIX',
      search_name_es: 'NETFLIX',
      image: require('../res/image/netflix.png'),
      video: `${uri}/netflix.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOTEBOOK',
      search_name_es: 'NOTEBOOK',
      image: require('../res/image/notebook.png'),
      video: `${uri}/notebook.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PÁGINA WEB',
      search_name_es: 'PÁGINA WEB',
      image: require('../res/image/pagina-web.png'),
      video: `${uri}/pagina-web.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PELÍCULA',
      search_name_es: 'PELICULA',
      image: require('../res/image/pelicula.png'),
      video: `${uri}/pelicula.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PENDRIVE',
      search_name_es: 'PENDRIVE',
      image: require('../res/image/pendrive.png'),
      video: `${uri}/pendrive.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PROYECTOR',
      search_name_es: 'PROYECTOR',
      image: require('../res/image/proyector.png'),
      video: `${uri}/proyector.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TABLET',
      search_name_es: 'TABLET',
      image: require('../res/image/tablet.png'),
      video: `${uri}/tablet.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TELÉFONO',
      search_name_es: 'TELEFONO',
      image: require('../res/image/telefono.png'),
      video: `${uri}/telefono.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TWITTER',
      search_name_es: 'TWITTER',
      image: require('../res/image/twitter.png'),
      video: `${uri}/twitter.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIDEO',
      search_name_es: 'VIDEO',
      image: require('../res/image/video.png'),
      video: `${uri}/video.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIDEOLLAMADA',
      search_name_es: 'VIDEOLLAMADA',
      image: require('../res/image/video-llamada.png'),
      video: `${uri}/videollamada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'WHATSAPP',
      search_name_es: 'WHATSAPP',
      image: require('../res/image/whatsapp.png'),
      video: `${uri}/whatsapp.mp4`,
      downloaded: false,
    },
    {
      name_es: 'WIFI',
      search_name_es: 'WIFI',
      image: require('../res/image/wifi.png'),
      video: `${uri}/wifi.mp4`,
      downloaded: false,
    },
    {
      name_es: 'YOUTUBE',
      search_name_es: 'YOUTUBE',
      image: require('../res/image/youtube.png'),
      video: `${uri}/youtube.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZOOM',
      search_name_es: 'ZOOM',
      image: require('../res/image/zoom.png'),
      video: `${uri}/zoom.mp4`,
      downloaded: false,
    },
  ],
});
