export const time = uri => ({
  name_es: '¿QUÉ HORA ES?',
  icon: require('../res/icon/que-hora-es.png'),
  videos: [
    {
      name_es: '¿QUÉ HORA ES?',
      search_name_es: '¿QUE HORA ES?',
      image: require('../res/image/que-hora-es.png'),
      video: `${uri}/que-hora-es.mp4`,
      downloaded: false,
    },
    {
      name_es: '... Y MEDIA',
      search_name_es: '... Y MEDIA',
      image: require('../res/image/y-media.png'),
      video: `${uri}/y-media.mp4`,
      downloaded: false,
    },
    {
      name_es: 'A LA MAÑANA',
      search_name_es: 'A LA MAÑANA',
      image: require('../res/image/a-la-manana.png'),
      video: `${uri}/a-la-manana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'A LA TARDE',
      search_name_es: 'A LA TARDE',
      image: require('../res/image/a-la-tarde.png'),
      video: `${uri}/a-la-tarde.mp4`,
      downloaded: false,
    },
    {
      name_es: 'A VECES',
      search_name_es: 'A VECES',
      image: require('../res/image/a-veces.png'),
      video: `${uri}/a-veces.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMUERZO',
      search_name_es: 'ALMUERZO',
      image: require('../res/image/almuerzo.png'),
      video: `${uri}/almuerzo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAFÉ',
      search_name_es: 'CAFE',
      image: require('../res/image/cafe.png'),
      video: `${uri}/cafe.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CENA',
      search_name_es: 'CENA',
      image: require('../res/image/cena.png'),
      video: `${uri}/cena.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESAYUNO',
      search_name_es: 'DESAYUNO',
      image: require('../res/image/desayuno.png'),
      video: `${uri}/desayuno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESPUÉS',
      search_name_es: 'DESPUES',
      image: require('../res/image/despues.png'),
      video: `${uri}/despues.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EN PUNTO',
      search_name_es: 'EN PUNTO',
      image: require('../res/image/en-punto.png'),
      video: `${uri}/en-punto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTRELLA',
      search_name_es: 'ESTRELLA',
      image: require('../res/image/estrella.png'),
      video: `${uri}/estrella.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HORA',
      search_name_es: 'HORA',
      image: require('../res/image/hora.png'),
      video: `${uri}/hora.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LUNA',
      search_name_es: 'LUNA',
      image: require('../res/image/luna.png'),
      video: `${uri}/luna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MENOS...',
      search_name_es: 'MENOS...',
      image: require('../res/image/menos.png'),
      video: `${uri}/menos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MERIENDA',
      search_name_es: 'MERIENDA',
      image: require('../res/image/merienda.png'),
      video: `${uri}/merienda.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MINUTO',
      search_name_es: 'MINUTO',
      image: require('../res/image/minuto.png'),
      video: `${uri}/minuto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RELOJ',
      search_name_es: 'RELOJ',
      image: require('../res/image/reloj.png'),
      video: `${uri}/reloj.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEGUNDO',
      search_name_es: 'SEGUNDO',
      image: require('../res/image/segundo.png'),
      video: `${uri}/segundo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SIEMPRE',
      search_name_es: 'SIEMPRE',
      image: require('../res/image/siempre.png'),
      video: `${uri}/siempre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TARDE',
      search_name_es: 'TARDE',
      image: require('../res/image/tarde.png'),
      video: `${uri}/tarde.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TEMPRANO',
      search_name_es: 'TEMPRANO',
      image: require('../res/image/temprano.png'),
      video: `${uri}/temprano.mp4`,
      downloaded: false,
    },
  ],
});
