export const where = uri => ({
  name_es: '¿DÓNDE VIVO?',
  icon: require('../res/icon/donde-vivo.png'),
  videos: [
    {
      name_es: 'ABORIGEN',
      search_name_es: 'ABORIGEN',
      image: require('../res/image/aborigen.png'),
      video: `${uri}/aborigen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ANTÁRTIDA ARGENTINA',
      search_name_es: 'ANTARTIDA ARGENTINA',
      image: require('../res/image/antartida-argentina.png'),
      video: `${uri}/antartida-argentina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARGENTINA',
      search_name_es: 'ARGENTINA',
      image: require('../res/image/argentina.png'),
      video: `${uri}/argentina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOLIVIA',
      search_name_es: 'BOLIVIA',
      image: require('../res/image/bolivia.png'),
      video: `${uri}/bolivia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BRASIL',
      search_name_es: 'BRASIL',
      image: require('../res/image/brasil.png'),
      video: `${uri}/brasil.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENOS AIRES',
      search_name_es: 'BUENOS AIRES',
      image: require('../res/image/buenos-aires.png'),
      video: `${uri}/buenos-aires.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CATAMARCA',
      search_name_es: 'CATAMARCA',
      image: require('../res/image/catamarca.png'),
      video: `${uri}/catamarca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHACO',
      search_name_es: 'CHACO',
      image: require('../res/image/chaco.png'),
      video: `${uri}/chaco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHILE',
      search_name_es: 'CHILE',
      image: require('../res/image/chile.png'),
      video: `${uri}/chile.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHUBUT',
      search_name_es: 'CHUBUT',
      image: require('../res/image/chubut.png'),
      video: `${uri}/chubut.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIUDAD',
      search_name_es: 'CIUDAD',
      image: require('../res/image/ciudad.png'),
      video: `${uri}/ciudad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CÓRDOBA',
      search_name_es: 'CORDOBA',
      image: require('../res/image/cordoba.png'),
      video: `${uri}/cordoba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORRIENTES',
      search_name_es: 'CORRIENTES',
      image: require('../res/image/corrientes.png'),
      video: `${uri}/corrientes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENTRE RÍOS',
      search_name_es: 'ENTRE RIOS',
      image: require('../res/image/entre-rios.png'),
      video: `${uri}/entre-rios.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTE',
      search_name_es: 'ESTE',
      image: require('../res/image/este.png'),
      video: `${uri}/este.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EXTRANJERO',
      search_name_es: 'EXTRANJERO',
      image: require('../res/image/extranjero.png'),
      video: `${uri}/extranjero.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FORMOSA',
      search_name_es: 'FORMOSA',
      image: require('../res/image/formosa.png'),
      video: `${uri}/formosa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ISLAS MALVINAS',
      search_name_es: 'ISLAS MALVINAS',
      image: require('../res/image/islas-malvinas.png'),
      video: `${uri}/islas-malvinas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUJUY',
      search_name_es: 'JUJUY',
      image: require('../res/image/jujuy.png'),
      video: `${uri}/jujuy.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LA PAMPA',
      search_name_es: 'LA PAMPA',
      image: require('../res/image/la-pampa.png'),
      video: `${uri}/la-pampa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LA RIOJA',
      search_name_es: 'LA RIOJA',
      image: require('../res/image/la-rioja.png'),
      video: `${uri}/la-rioja.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MENDOZA',
      search_name_es: 'MENDOZA',
      image: require('../res/image/mendoza.png'),
      video: `${uri}/mendoza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MISIONES',
      search_name_es: 'MISIONES',
      image: require('../res/image/misiones.png'),
      video: `${uri}/misiones.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MUNDO',
      search_name_es: 'MUNDO',
      image: require('../res/image/mundo.png'),
      video: `${uri}/mundo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NEUQUÉN',
      search_name_es: 'NEUQUEN',
      image: require('../res/image/neuquen.png'),
      video: `${uri}/neuquen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NORTE',
      search_name_es: 'NORTE',
      image: require('../res/image/norte.png'),
      video: `${uri}/norte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OESTE',
      search_name_es: 'OESTE',
      image: require('../res/image/oeste.png'),
      video: `${uri}/oeste.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OTROS PAÍSES',
      search_name_es: 'OTROS PAISES',
      image: require('../res/image/otros-paises.png'),
      video: `${uri}/otros-paises.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARAGUAY',
      search_name_es: 'PARAGUAY',
      image: require('../res/image/paraguay.png'),
      video: `${uri}/paraguay.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PROVINCIAS',
      search_name_es: 'PROVINCIAS',
      image: require('../res/image/provincias.png'),
      video: `${uri}/provincias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PUEBLO',
      search_name_es: 'PUEBLO',
      image: require('../res/image/pueblo.png'),
      video: `${uri}/pueblo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RIO NEGRO',
      search_name_es: 'RIO NEGRO',
      image: require('../res/image/rio-negro.png'),
      video: `${uri}/rio-negro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALTA',
      search_name_es: 'SALTA',
      image: require('../res/image/salta.png'),
      video: `${uri}/salta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN JUAN',
      search_name_es: 'SAN JUAN',
      image: require('../res/image/san-juan.png'),
      video: `${uri}/san-juan.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN LUIS',
      search_name_es: 'SAN LUIS',
      image: require('../res/image/san-luis.png'),
      video: `${uri}/san-luis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTA CRUZ',
      search_name_es: 'SANTA CRUZ',
      image: require('../res/image/santa-cruz.png'),
      video: `${uri}/santa-cruz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTA FÉ',
      search_name_es: 'SANTA FE',
      image: require('../res/image/santa-fe.png'),
      video: `${uri}/santa-fe.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTIAGO DEL ESTERO',
      search_name_es: 'SANTIAGO DEL ESTERO',
      image: require('../res/image/santiago-del-estero.png'),
      video: `${uri}/santiago-del-estero.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUR',
      search_name_es: 'SUR',
      image: require('../res/image/sur.png'),
      video: `${uri}/sur.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIERRA DEL FUEGO',
      search_name_es: 'TIERRA DEL FUEGO',
      image: require('../res/image/tierra-del-fuego.png'),
      video: `${uri}/tierra-del-fuego.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TUCUMÁN',
      search_name_es: 'TUCUMAN',
      image: require('../res/image/tucuman.png'),
      video: `${uri}/tucuman.mp4`,
      downloaded: false,
    },
    {
      name_es: 'URUGUAY',
      search_name_es: 'URUGUAY',
      image: require('../res/image/uruguay.png'),
      video: `${uri}/uruguay.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIAJAR',
      search_name_es: 'VIAJAR',
      image: require('../res/image/viajar.png'),
      video: `${uri}/viajar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIVIR',
      search_name_es: 'VIVIR',
      image: require('../res/image/vivir.png'),
      video: `${uri}/vivir.mp4`,
      downloaded: false,
    },
  ],
});
